project_name: local-pv-cleaner

builds:
  - id: local-pv-cleaner
    binary: local-pv-cleaner
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates: ["ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/kavinraja-g/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/kavinraja-g/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache
  - image_templates: ["ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/kavinraja-g/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/kavinraja-g/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache

docker_manifests:
  - name_template: ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/kavinraja-g/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/kavinraja-g/{{ .ProjectName }}:{{ .Version }}-arm64v8