apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: local-pv-cleaner
    app.kubernetes.io/managed-by: kustomize
  name: local-pv-cleaner-leader-election-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: local-pv-cleaner-leader-election-role
subjects:
- kind: ServiceAccount
  name: local-pv-cleaner
  namespace: local-pv-cleaner
