---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-pv-cleaner
  namespace: local-pv-cleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-pv-cleaner
  template:
    metadata:
      labels:
        app: local-pv-cleaner
    spec:
      serviceAccountName: local-pv-cleaner
      containers:
        - name: local-pv-cleaner
          image: ghcr.io/kavinraja-g/local-pv-cleaner:latest
          imagePullPolicy: Always
          args:
            - "--dry-run=true"
            - "--node-selector-keys=topology.topolvm.io/node"
          resources:
            requests:
              cpu: "25m"
              memory: "100Mi"
            limits:
              memory: "256Mi"
