---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-pv-cleaner
  namespace: local-pv-cleaner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: local-pv-cleaner-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: local-pv-cleaner-rolebinding
  namespace: local-pv-cleaner
subjects:
  - kind: ServiceAccount
    name: local-pv-cleaner
    namespace: local-pv-cleaner
roleRef:
  kind: Role
  name: local-pv-cleaner-role
  apiGroup: rbac.authorization.k8s.io
